### PR TITLE
Fix scope of analyzed changes

### PR DESCRIPTION
**Pull request by fixe**
This PR fixes a bug which was displaying a possible fixup for unchanged lines.

### CODE REVIEW

**Comment by keis** [comment]
Getting suggestions from some unchanged lines is actually intentional as it will give suggestions for some pretty common cases like appending items to list written over multiple lines. Are you running into a lot of annoying false positives from this?

looks like there might be some otherwise interesting fixes from the commit but I'm not following the expr thing at all. Wouldn't that always be 1?

**Comment by fixe** [comment]
@keis: without the `--no-prefix` the following error is thrown:

```
fatal: no such path c/<filename>

**Comment by fixe** [comment]
I'll close this PR and focus on the real issue for now.

**Comment by fixe** [comment]
Note: without this change I'm getting the following error:

```
fatal: More than one commit to dig from HEAD and <sha>?

**Pull request closed without merging**
