### PR TITLE
Use bash from PATH for brew

### PR DESCRIPTION
**Pull request by glensc**
Use `bash` from `$PATH`, to find newer `bash` on macOS that `--commit` feature requires for `readarray`.

Using hardcoded path for `bash` results fatal error with `--commit` on macOS:

```
➔ git fixup
/usr/local/bin/git-fixup: line 73: readarray: command not found
```

Problem is that `/bin/bash` is very old on that platform, as is never going to be updated to a newer version due to license change in newer bash versions (GPL v3)

```
➔ head -n1 /usr/local/bin/git-fixup
#!/bin/bash
➔ which bash
/usr/local/bin/bash

➔ /bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)
Copyright (C) 2007 Free Software Foundation, Inc.

➔ /usr/local/bin/bash --version
GNU bash, version 5.0.11(1)-release (x86_64-apple-darwin18.6.0)
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
➔
```

**IMPORTANT**: Please tag new version so could update brew users could get updated formula as well.

### CODE REVIEW

**Comment by keis** [comment]
Thanks for the PR @glensc

**Comment by keis** [comment]
There's now a v1.3.0 tag

**Comment by glensc** [comment]
Created homebrew PR: https://github.com/Homebrew/homebrew-core/pull/50606

Somewhy I assumed it's automatic, but it's not...

**Comment by keis** [comment]
Thanks again @glensc

**Comment by glensc** [comment]
brew dudes suggest to setup github action to automate release syncing:
- https://github.com/Homebrew/homebrew-core/pull/50606#issuecomment-590108097

**Pull request merged**
