### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by fixe**

### CODE REVIEW

**Comment by keis** [comment]
Without a file ending github gets all confused and wont do a pretty render on the project page

**Comment by fixe** [comment]
@keis what about renaming the `README` file to `README.md`?

**Comment by keis** [comment]
yeah, I'm cool with that. the original was restructed text so please check that the syntax makes sense

**Comment by fixe** [comment]
@keis: updated. I'll add some info the the README in another PR (such as a gif showing an example).

**Comment by keis** [comment]
Thanks. a gif would be brilliant to have :)

the h3 used in changes does not render properly anymore other than that it looks good

**Comment by fixe** [comment]
@keis: updated.

**Pull request merged**
