### PR TITLE
Add screenshot to README

### PR DESCRIPTION
**Pull request by fixe**

### CODE REVIEW

**Comment by keis** [comment]
Sweet! thanks

Would be great if you could bundle the file and use it with a relative link instead as I'm not to sure how much to rely on the githubusercontent stuff to stay forever

should be something like this I think
git fixup

**Comment by fixe** [comment]
@keis I don't think that they remove uploaded images from their servers. We can add it later if they remove them.

**Comment by fixe** [comment]
The thing is: I don't think we should add the file to the root of the project and creating a `docs` folder only containing this image seems too much for me. WDYS?

**Comment by keis** [comment]
Yeah true. Maybe I'm overthinking it. And anyway it's not like the picture is critical to the operation of the script

**Pull request merged**
